version: '3'

services:
  app:
    build: ./go/
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    depends_on:
      - db
  
  db:
    image: mysql:8
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: go_mysql8_development